# Generated by Django 5.1.5 on 2026-03-11 00:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enseignant', '0001_initial'),
        ('gestion_academique', '0001_initial'),
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_note_1', models.BooleanField(default=True, help_text='Cocher si la note 1 est prise en compte')),
                ('use_note_2', models.BooleanField(default=True, help_text='Cocher si la note 2 est prise en compte')),
                ('use_note_3', models.BooleanField(default=True, help_text='Cocher si la note 3 est prise en compte')),
                ('use_note_partiel', models.BooleanField(default=True, help_text='Cocher si la note du partiel est prise en compte')),
                ('partiel_uniquement', models.BooleanField(default=False, help_text='Cocher si uniquement la note du partiel est prise en compte')),
                ('fichier', models.FileField(upload_to='notes/fichiers/')),
                ('coefficient_note_partiel', models.IntegerField(default=1)),
                ('coeeficient_matiere', models.IntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classe_note', to='gestion_academique.classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_matiere', to='enseignant.contratenseignant')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_1', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('note_2', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('note_3', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('note_partiel', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)])),
                ('non_classe', models.BooleanField(default=False, help_text="Cocher si l'étudiant est non classé dans la matière")),
                ('session', models.CharField(choices=[('SESSION 1', 'SESSION 1'), ('SESSION 2', 'SESSION 2')], default='SESSION 1', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('moyenne', models.FloatField(default=0, editable=False)),
                ('moyenne_coefficient', models.FloatField(default=0, editable=False)),
                ('moyenne_unite', models.FloatField(default=0, editable=False)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insription_note', to='inscription.inscription')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_resultat', to='evaluations.note')),
            ],
        ),
    ]
