# Generated by Django 5.1.5 on 2025-03-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultat',
            name='non_classe',
            field=models.BooleanField(default=False, help_text="Cocher si l'étudiant est non classé dans la matière"),
        ),
    ]
