# Generated by Django 5.1.5 on 2025-09-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_alter_resultat_non_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultat',
            name='moyenne_unite',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
