# Generated by Django 5.1.5 on 2026-03-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_resultat_moyenne_unite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultat',
            name='moyenne_unite',
        ),
        migrations.AlterField(
            model_name='resultat',
            name='non_classe',
            field=models.BooleanField(default=False, help_text="Cocher si l'etudiant est non classé dans la matiere"),
        ),
    ]
