# Generated by Django 5.1.5 on 2026-03-11 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0001_initial'),
        ('gestion_academique', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hta', models.BooleanField(default=False)),
                ('diabete', models.BooleanField(default=False)),
                ('asthme', models.BooleanField(default=False)),
                ('drepanocytose', models.BooleanField(default=False)),
                ('ulcere', models.BooleanField(default=False)),
                ('epilepsie', models.BooleanField(default=False)),
                ('autre_antecedents', models.CharField(blank=True, max_length=250, null=True)),
                ('pere_hta', models.BooleanField(default=False)),
                ('pere_diabete', models.BooleanField(default=False)),
                ('pere_asthme', models.BooleanField(default=False)),
                ('pere_drepanocytose', models.BooleanField(default=False)),
                ('pere_ulcere', models.BooleanField(default=False)),
                ('pere_epilepsie', models.BooleanField(default=False)),
                ('pere_autre_antecedents', models.CharField(blank=True, max_length=250, null=True)),
                ('mere_hta', models.BooleanField(default=False)),
                ('mere_diabete', models.BooleanField(default=False)),
                ('mere_asthme', models.BooleanField(default=False)),
                ('mere_drepanocytose', models.BooleanField(default=False)),
                ('mere_ulcere', models.BooleanField(default=False)),
                ('mere_epilepsie', models.BooleanField(default=False)),
                ('mere_autre_antecedents', models.CharField(blank=True, max_length=250, null=True)),
                ('tabac', models.BooleanField(default=False)),
                ('alcool', models.BooleanField(default=False)),
                ('stupefiant', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='etudiants.etudiant')),
            ],
            options={
                'verbose_name': 'Dossier Medical',
                'verbose_name_plural': 'Dossier Medicals',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TA', models.CharField(max_length=50)),
                ('pouls', models.CharField(max_length=50)),
                ('Temperature', models.CharField(max_length=50)),
                ('FR', models.CharField(max_length=50)),
                ('Sao2', models.CharField(max_length=50)),
                ('Glasgow', models.CharField(max_length=50)),
                ('poids', models.CharField(blank=True, max_length=3, null=True)),
                ('motif_de_la_consultation', models.TextField(blank=True, null=True)),
                ('histoire_de_la_mamdie', models.TextField(blank=True, null=True)),
                ('examen_physique', models.TextField(blank=True, null=True)),
                ('hypotheses_diagnostic', models.TextField(blank=True, null=True)),
                ('examens_paracliniques', models.TextField(blank=True, null=True)),
                ('diagnostic_retenu', models.TextField(blank=True, null=True)),
                ('traitement', models.TextField(blank=True, null=True)),
                ('evolution', models.TextField(blank=True, null=True)),
                ('rendez_vous', models.DateField(blank=True, null=True)),
                ('arret_de_travail', models.BooleanField(default=False)),
                ('debut_arret_travail', models.DateField(blank=True, null=True)),
                ('fin_arret_travail', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annee_consultations', to='gestion_academique.anneeacademique')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medecin_consultations', to=settings.AUTH_USER_MODEL)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_consultations', to='medicale.dossiermedical')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
            },
        ),
    ]
