# Generated by Django 5.1.5 on 2025-12-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedical',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
