# Generated by Django 5.1.5 on 2025-12-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicale', '0002_dossiermedical_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedical',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
