# Generated by Django 4.2.3 on 2024-04-09 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_academique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('volume_horaire', models.FloatField(default=0)),
                ('progression', models.FloatField(default=0)),
                ('taux_horaire', models.IntegerField(default=0)),
                ('support', models.FileField(blank=True, null=True, upload_to='cours/support')),
                ('syllabus', models.FileField(blank=True, null=True, upload_to='cours/syllabus')),
                ('support_depose', models.BooleanField(default=False)),
                ('syllabus_depose', models.BooleanField(default=False)),
                ('cahier_de_texte', models.BooleanField(default=False)),
                ('notes', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('demande_accompte', models.BooleanField(default=False)),
                ('demande_traitee', models.BooleanField(default=False)),
                ('numero_cheque', models.CharField(max_length=50)),
                ('cheque_retire', models.BooleanField(default=False)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annee_contrat', to='gestion_academique.anneeacademique')),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classe_contrat', to='gestion_academique.classe')),
            ],
            options={
                'verbose_name': 'Contrat Enseignant',
                'verbose_name_plural': 'Contrat Enseignants',
                'ordering': ['matiere__unite__semestre', 'matiere__nom'],
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('cv_et_document', models.FileField(blank=True, null=True, upload_to='enseignant/dossier')),
                ('domaine', models.TextField()),
                ('numero_cni', models.CharField(max_length=50)),
                ('date_de_naissance', models.DateField()),
                ('lieu_de_naissance', models.CharField(max_length=50)),
                ('nationalite', django_countries.fields.CountryField(max_length=2)),
                ('domicile', models.CharField(max_length=50)),
                ('statut_enseignant', models.CharField(choices=[('Titulaire', 'Titulaire'), ('Vacataire', 'Vacataire')], max_length=11)),
                ('sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], max_length=10)),
                ('situations', models.CharField(choices=[('Célibataire', 'Célibataire'), ('Veuf(ve)', 'Veuf(ve)'), ('Marié(e)', 'Marié(e)'), ('Divorcé(e)', 'Divorcé(e)')], max_length=20)),
                ('contact', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(editable=False, max_length=10)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enseignant_etablissement', to='gestion_academique.etablissement')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
            },
        ),
        migrations.CreateModel(
            name='TravauxDirige',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_horaire', models.FloatField(default=0)),
                ('taux_horaire', models.IntegerField(default=0)),
                ('progression', models.FloatField(default=0)),
                ('paye', models.BooleanField(default=False)),
                ('contrat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contratd_td', to='enseignant.contratenseignant')),
            ],
            options={
                'verbose_name': 'Travaux Dirige',
                'verbose_name_plural': 'Travaux Diriges',
            },
        ),
        migrations.CreateModel(
            name='Rib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banque', models.CharField(max_length=50)),
                ('document', models.FileField(blank=True, null=True, upload_to='enseignants/rib')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('default', models.BooleanField(default=True)),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enseignant_rib', to='enseignant.enseignant')),
            ],
            options={
                'verbose_name': 'Rib',
                'verbose_name_plural': 'Ribs',
            },
        ),
        migrations.AddField(
            model_name='contratenseignant',
            name='enseignant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enseignant_contrat', to='enseignant.enseignant'),
        ),
        migrations.AddField(
            model_name='contratenseignant',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filiere_contrat', to='gestion_academique.filiere'),
        ),
        migrations.AddField(
            model_name='contratenseignant',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matiere_contrat', to='gestion_academique.matiere'),
        ),
        migrations.AddField(
            model_name='contratenseignant',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='niveau_contrat', to='gestion_academique.niveau'),
        ),
    ]
