# Generated by Django 5.1.5 on 2025-12-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enseignant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='code',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='contact',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='sexe',
            field=models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], max_length=50),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='situations',
            field=models.CharField(choices=[('Célibataire', 'Célibataire'), ('Veuf(ve)', 'Veuf(ve)'), ('Marié(e)', 'Marié(e)'), ('Divorcé(e)', 'Divorcé(e)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='statut_enseignant',
            field=models.CharField(choices=[('Titulaire', 'Titulaire'), ('Vacataire', 'Vacataire')], max_length=50),
        ),
    ]
