# Generated by Django 5.1.5 on 2025-11-12 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_academique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploisDutemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('classe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classe_programme', to='gestion_academique.classe')),
            ],
            options={
                'verbose_name': 'Emplois Du temps',
                'verbose_name_plural': 'Emplois Du temps',
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('matiere', models.CharField(max_length=255)),
                ('salle', models.CharField(max_length=255)),
                ('jour', models.CharField(choices=[('LUNDI', 'LUNDI'), ('MARDI', 'MARDI'), ('MERCREDI', 'MERCREDI'), ('JEUDI', 'JEUDI'), ('VENDREDI', 'VENDREDI'), ('SAMEDI', 'SAMEDI'), ('DIMANCHE', 'DIMANCHE')], max_length=10)),
                ('debut', models.CharField(max_length=255)),
                ('fin', models.CharField(max_length=255)),
                ('enseignant', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('emplois_du_temps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois_du_temps_matiere', to='emplois_du_temps.emploisdutemps')),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
                'ordering': ['date'],
            },
        ),
    ]
