# Generated by Django 4.2.3 on 2024-04-09 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enseignant', '0001_initial'),
        ('gestion_academique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploisDutemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('classe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classe_programme', to='gestion_academique.classe')),
            ],
            options={
                'verbose_name': 'Emplois Du temps',
                'verbose_name_plural': 'Emplois Du temps',
            },
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('jour', models.CharField(choices=[('LUNDI', 'LUNDI'), ('MARDI', 'MARDI'), ('MERCREDI', 'MERCREDI'), ('JEUDI', 'JEUDI'), ('VENDREDI', 'VENDREDI'), ('SAMEDI', 'SAMEDI'), ('DIMANCHE', 'DIMANCHE')], max_length=10)),
                ('debut', models.TimeField()),
                ('fin', models.TimeField()),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('emplois_du_temps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois_du_temps_matiere', to='emplois_du_temps.emploisdutemps')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplois_du_temps_matiere', to='enseignant.contratenseignant')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salle_cours', to='gestion_academique.salle')),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
                'ordering': ['date'],
            },
        ),
    ]
