# Generated by Django 4.2.3 on 2024-10-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplois_du_temps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='enseignant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='debut',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='programme',
            name='fin',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='programme',
            name='matiere',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='programme',
            name='salle',
            field=models.CharField(max_length=255),
        ),
    ]
