# Generated by Django 5.1.5 on 2025-11-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('position', models.CharField(blank=True, help_text='Ex: Proviseur, Directeur, Responsable pédagogique, Comptable…', max_length=120)),
                ('school_name', models.CharField(max_length=200)),
                ('school_type', models.CharField(choices=[('MATERNELLE', 'École maternelle'), ('PRIMAIRE', 'École primaire'), ('SECONDAIRE', 'Collège / Lycée'), ('SUPERIEUR', 'Enseignement supérieur / Université'), ('FORMATION', 'Centre de formation'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('students_count', models.CharField(blank=True, help_text='Ex: 300, 500–1000, +2000…', max_length=50)),
                ('preferred_slot', models.CharField(blank=True, help_text='Ex: Lundi matin, Soir après les cours, Week-end…', max_length=100)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
