# Generated by Django 5.1.5 on 2025-11-12 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0001_initial'),
        ('gestion_academique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcour', models.CharField(choices=[('CYCLE UNIVERSITAIRE', 'CYCLE UNIVERSITAIRE'), ('CYCLE PROFESSIONNEL JOUR', 'CYCLE PROFESSIONNEL JOUR'), ('CYCLE PROFESSIONNEL SOIR', 'CYCLE PROFESSIONNEL SOIR'), ('CYCLE EN LIGNE', 'CYCLE EN LIGNE')], max_length=200)),
                ('nature', models.CharField(choices=[('INSCRIPTION', 'INSCRIPTION'), ('RE-INSCRIPTION', 'RE-INSCRIPTION')], max_length=200)),
                ('frais', models.IntegerField()),
                ('paye', models.IntegerField(default=0)),
                ('code_parrain', models.CharField(blank=True, max_length=10, null=True)),
                ('piece', models.BooleanField(default=False, help_text="Cocher si l'étudiant a déposé une copie de sa pièce")),
                ('passe_le_bts', models.BooleanField(default=False, help_text="Cocher si l'étudiant passe le BTS cette année")),
                ('extrait', models.BooleanField(default=False, help_text="Cocher si l'étudiant a déposé son extrait")),
                ('bac', models.BooleanField(default=False, help_text="Cocher si l'étudiant a déposé son bac")),
                ('fiche_orientation', models.BooleanField(default=False, help_text="Cocher si l'étudiant a déposé sa fiche d'orientation")),
                ('photo', models.BooleanField(default=False, help_text="Cocher si l'étudiant a déposé les photos d'identité")),
                ('polo', models.BooleanField(default=False, help_text="Cocher si l'étudiant à recu son Polo")),
                ('macaron', models.BooleanField(default=False, help_text="Cocher si l'étudiant à recu son macaron")),
                ('cravate', models.BooleanField(default=False, help_text="Cocher si l'étudiant à recu sa cravate")),
                ('tissu', models.BooleanField(default=False, help_text="Cocher si l'étudiant à recu son tissu")),
                ('rame', models.BooleanField(default=False, help_text="Cocher si l'étudiant à déposé ses rames")),
                ('marqueur', models.BooleanField(default=False, help_text="Cocher si l'étudiant à déposé ses marqueurs")),
                ('active', models.BooleanField(default=False)),
                ('nouvel_etudiant', models.BooleanField(default=False, help_text="Cocher si l'étudiant est s'inscris pour la première fois dans l'établissement")),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('absence_semestre1', models.IntegerField(default=0)),
                ('absence_semestre2', models.IntegerField(default=0)),
                ('carte_etudiant', models.BooleanField(default=False, help_text="Cocher si l'étudiant a recu sa carte etudiant")),
                ('confirmed', models.BooleanField(default=False)),
                ('solded', models.BooleanField(default=False)),
                ('quantite_rame', models.IntegerField(default=0)),
                ('quantite_marqueur', models.IntegerField(default=0)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscription_annee', to='gestion_academique.anneeacademique')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscription_classe', to='gestion_academique.classe')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscription_etudiant', to='etudiants.etudiant')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscription_filiere', to='gestion_academique.filiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscription_niveau', to='gestion_academique.niveau')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField(default=0)),
                ('source', models.CharField(blank=True, max_length=150, null=True)),
                ('reference', models.CharField(blank=True, max_length=150, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('confirmation_finance', models.BooleanField(default=False)),
                ('non_wave_direct_api', models.BooleanField(default=False)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('effectue_par', models.CharField(blank=True, max_length=50, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('wave_launch_url', models.CharField(blank=True, max_length=250, null=True)),
                ('wave_id', models.CharField(blank=True, max_length=250, null=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscription_paiement', to='inscription.inscription')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
    ]
