# Generated by Django 4.2.3 on 2024-07-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='bac',
            field=models.BooleanField(default=False, help_text="Cocher si l'étudiant a déposé son bac"),
        ),
        migrations.AddField(
            model_name='inscription',
            name='code_parrain',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='extrait',
            field=models.BooleanField(default=False, help_text="Cocher si l'étudiant a déposé son extrait"),
        ),
        migrations.AddField(
            model_name='inscription',
            name='fiche_orientation',
            field=models.BooleanField(default=False, help_text="Cocher si l'étudiant a déposé sa fiche d'orientation"),
        ),
        migrations.AddField(
            model_name='inscription',
            name='photo',
            field=models.BooleanField(default=False, help_text="Cocher si l'étudiant a déposé les photos d'identité"),
        ),
        migrations.AddField(
            model_name='inscription',
            name='piece',
            field=models.BooleanField(default=False, help_text="Cocher si l'étudiant a déposé une copie de sa pièce"),
        ),
    ]
