# Generated by Django 4.2.3 on 2024-07-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0002_inscription_bac_inscription_code_parrain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='passe_le_bts',
            field=models.BooleanField(default=False, help_text="Cocher si l'étudiant passe le BTS cette année"),
        ),
    ]
