# Generated by Django 4.2.3 on 2024-09-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0003_inscription_passe_le_bts'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='quantite_marqueur',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inscription',
            name='quantite_rame',
            field=models.IntegerField(default=0),
        ),
    ]
