# Generated by Django 4.2.3 on 2024-12-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0004_inscription_quantite_marqueur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='confirmation_finance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paiement',
            name='effectue_par',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paiement',
            name='non_wave_direct_api',
            field=models.BooleanField(default=False),
        ),
    ]
