# Generated by Django 4.2.3 on 2024-12-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0005_paiement_confirmation_finance_paiement_effectue_par_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
