# Generated by Django 4.2.3 on 2024-12-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0006_alter_paiement_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
