# Generated by Django 4.2.3 on 2024-12-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0007_alter_paiement_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
