# Generated by Django 5.1.5 on 2026-03-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0009_alter_paiement_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paiement',
            name='confirmation_finance',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='effectue_par',
        ),
        migrations.RemoveField(
            model_name='paiement',
            name='non_wave_direct_api',
        ),
    ]
