# Generated by Django 4.2.3 on 2024-04-09 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.IntegerField()),
                ('fin', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Année Academique',
                'verbose_name_plural': 'Années Academiques',
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('sigle', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=150)),
                ('full_name', models.TextField()),
                ('logo', models.FileField(blank=True, null=True, upload_to='etablissement/logo')),
                ('cachet_scolarite', models.FileField(blank=True, null=True, upload_to='etablissement/cachez_scolarite')),
                ('footer_bull', models.TextField()),
                ('contact', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('site', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Etablissement',
                'verbose_name_plural': 'Etablissements',
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('parcour', models.CharField(choices=[('UNIVERSITAIRE', 'UNIVERSITAIRE'), ('PROFESSIONNEL', 'PROFESSIONNEL')], max_length=200)),
                ('sigle', models.CharField(max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etablissement_filiere', to='gestion_academique.etablissement')),
            ],
            options={
                'verbose_name': 'Filiere',
                'verbose_name_plural': 'Filieres',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Maquette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('maquette_universitaire', models.BooleanField(default=False)),
                ('maquette_professionnel_jour', models.BooleanField(default=False)),
                ('maquette_professionnel_soir', models.BooleanField(default=False)),
                ('maquette_cours_en_ligne', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquette_annee_academemique', to='gestion_academique.anneeacademique')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquette_etablissement', to='gestion_academique.etablissement')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquette_filiere', to='gestion_academique.filiere')),
            ],
            options={
                'verbose_name': 'Maquette',
                'verbose_name_plural': 'Maquettes',
            },
        ),
        migrations.CreateModel(
            name='UniteEnseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('semestre', models.CharField(choices=[('SEMESTRE 1', 'SEMESTRE 1'), ('SEMESTRE 2', 'SEMESTRE 2')], max_length=200)),
                ('categorie', models.CharField(choices=[('CONNAISSANCE FONDEMENTALE', 'CONNAISSANCE FONDEMENTALE'), ('METHODOLOGIE', 'METHODOLOGIE'), ('CULTURE GENERALE', 'CULTURE GENERALE')], max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('maquette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ue_maquette', to='gestion_academique.maquette')),
            ],
            options={
                'verbose_name': 'Unité Enseignement',
                'verbose_name_plural': 'Unités Enseignements',
            },
        ),
        migrations.CreateModel(
            name='StudentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='gestion_academique.etablissement')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('capacite', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles', to='gestion_academique.etablissement')),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etablissement_niveau', to='gestion_academique.etablissement')),
            ],
            options={
                'verbose_name': 'Niveau',
                'verbose_name_plural': 'Niveaux',
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('coefficient', models.IntegerField()),
                ('volume_horaire', models.IntegerField(default=0)),
                ('taux_horaire', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('maquette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matiere_maquette', to='gestion_academique.maquette')),
                ('unite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matiere_ue', to='gestion_academique.uniteenseignement')),
            ],
            options={
                'verbose_name': 'Matiere',
                'verbose_name_plural': 'Matieres',
            },
        ),
        migrations.AddField(
            model_name='maquette',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquette_niveau', to='gestion_academique.niveau'),
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('classe_universitaire', models.BooleanField(default=False, help_text='Cochez si la classe est une classe universitaire')),
                ('classe_professionnelle_jour', models.BooleanField(default=False, help_text='Cochez si la classe est une classe professionnelle jour')),
                ('classe_professionnelle_soir', models.BooleanField(default=False, help_text='Cochez si la classe est une classe professionnelle soir')),
                ('classe_online', models.BooleanField(default=False, help_text='Cochez si la classe est une classe en ligne')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('closed', models.BooleanField(default=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classe_annee_academique', to='gestion_academique.anneeacademique')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classe_filiere', to='gestion_academique.filiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classe_niveau', to='gestion_academique.niveau')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='anneeacademique',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annee_academiques', to='gestion_academique.etablissement'),
        ),
    ]
