# Generated by Django 5.1.5 on 2025-11-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academique', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etablissement',
            options={'ordering': ['-created'], 'verbose_name': 'Etablissement', 'verbose_name_plural': 'Etablissements'},
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='cachet_scolarite',
            field=models.FileField(blank=True, help_text='Cachet utilisé pour les documents de scolarité.', null=True, upload_to='etablissement/cachet_scolarite'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='contact',
            field=models.CharField(help_text="Numéro de téléphone principal de l'établissement.", max_length=254),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='email',
            field=models.EmailField(help_text='Adresse email principale (ex. contact@ecole.ci).', max_length=254),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='footer_bull',
            field=models.TextField(help_text='Texte de pied de page pour les bulletins et relevés.'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='logo',
            field=models.FileField(blank=True, help_text="Logo officiel de l'établissement.", null=True, upload_to='etablissement/logo'),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='site',
            field=models.URLField(help_text='Adresse du site web (ex. https://www.ecole.ci).', max_length=254),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='wave_api_key',
            field=models.TextField(blank=True, help_text='Clé API Wave pour les paiements (optionnel).', null=True),
        ),
    ]
