# Generated by Django 4.2.3 on 2024-08-30 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionDiplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_diplome_etablissements', to='gestion_academique.etablissement')),
            ],
            options={
                'verbose_name': 'Session Diplome',
                'verbose_name_plural': 'Session Diplome',
            },
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=155)),
                ('prenom', models.CharField(max_length=155)),
                ('date_de_naissance', models.DateField()),
                ('lieu_de_naissance', models.CharField(max_length=155)),
                ('contact1', models.CharField(blank=True, max_length=50, null=True)),
                ('contact2', models.CharField(blank=True, max_length=50, null=True)),
                ('diplome', models.CharField(max_length=155)),
                ('niveau', models.CharField(choices=[('LICENCE', 'LICENCE'), ('MASTER', 'MASTER')], max_length=50)),
                ('annee_academique', models.CharField(max_length=50)),
                ('date_soutenance', models.CharField(max_length=50)),
                ('session_soutenance', models.CharField(max_length=50)),
                ('cycle', models.CharField(choices=[('PROFESSIONNEL', 'PROFESSIONNEL'), ('UNIVERSITAIRE', 'UNIVERSITAIRE')], max_length=50)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Diplome_session_two', to='gestion_academique.sessiondiplome')),
            ],
            options={
                'verbose_name': 'Diplome',
                'verbose_name_plural': 'Diplomes',
            },
        ),
    ]
