# Generated by Django 4.2.3 on 2024-09-23 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academique', '0002_sessiondiplome_diplome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus', to='gestion_academique.etablissement')),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campuss',
            },
        ),
        migrations.AddField(
            model_name='salle',
            name='campus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='salle_campus', to='gestion_academique.campus'),
            preserve_default=False,
        ),
    ]
