# Generated by Django 4.2.3 on 2024-09-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academique', '0003_campus_salle_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='wave_api_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
