# Generated by Django 4.2.3 on 2024-10-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academique', '0004_etablissement_wave_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='is_college',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='uniteenseignement',
            name='semestre',
            field=models.CharField(choices=[('SEMESTRE 1', 'SEMESTRE 1'), ('SEMESTRE 2', 'SEMESTRE 2'), ('SEMESTRE 3', 'SEMESTRE 3')], max_length=200),
        ),
    ]
