# Generated by Django 4.2.3 on 2024-10-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academique', '0005_etablissement_is_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplome',
            name='sexe',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
