# Generated by Django 4.2.3 on 2024-10-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academique', '0006_diplome_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='contact_enseignant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='matiere',
            name='enseignant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
