# Generated by Django 4.2.3 on 2024-10-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academique', '0007_matiere_contact_enseignant_matiere_enseignant'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='taux_horaire_td',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matiere',
            name='volume_horaire_td',
            field=models.IntegerField(default=0),
        ),
    ]
