# Generated by Django 4.2.3 on 2024-11-10 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academique', '0008_matiere_taux_horaire_td_matiere_volume_horaire_td'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasseProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enseignant', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('cours_en_tronc_commun', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('volume_realise', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Classe Progression',
                'verbose_name_plural': 'Classe Progressions',
            },
        ),
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ['annee_academique', 'filiere', 'niveau', 'nom'], 'verbose_name': 'Classe', 'verbose_name_plural': 'Classes'},
        ),
        migrations.CreateModel(
            name='Pointage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_realise', models.CharField(max_length=50)),
                ('observation', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression_matiere', to='gestion_academique.classeprogression')),
            ],
            options={
                'verbose_name': 'Pointage',
                'verbose_name_plural': 'Pointages',
            },
        ),
        migrations.AddField(
            model_name='classeprogression',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression_matiere_classe', to='gestion_academique.classe'),
        ),
        migrations.AddField(
            model_name='classeprogression',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matiere_classe_progress', to='gestion_academique.matiere'),
        ),
    ]
