# Generated by Django 4.2.3 on 2024-11-21 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academique', '0009_classeprogression_alter_classe_options_pointage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ['niveau', 'nom'], 'verbose_name': 'Classe', 'verbose_name_plural': 'Classes'},
        ),
    ]
