# Generated by Django 4.2.3 on 2024-11-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academique', '0010_alter_classe_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='classeprogression',
            name='note_deposee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classeprogression',
            name='paiement_effectue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classeprogression',
            name='piece',
            field=models.FileField(blank=True, null=True, upload_to='enseignant/piece'),
        ),
        migrations.AddField(
            model_name='classeprogression',
            name='rib',
            field=models.FileField(blank=True, null=True, upload_to='enseignant/rib'),
        ),
        migrations.AddField(
            model_name='classeprogression',
            name='support',
            field=models.FileField(blank=True, null=True, upload_to='enseignant/support'),
        ),
        migrations.AddField(
            model_name='classeprogression',
            name='syllabys',
            field=models.FileField(blank=True, null=True, upload_to='enseignant/syllabus'),
        ),
    ]
