# Generated by Django 4.2.3 on 2024-11-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academique', '0011_classeprogression_note_deposee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classeprogression',
            name='demande_de_paiement_initie',
            field=models.BooleanField(default=False),
        ),
    ]
