# Generated by Django 4.2.3 on 2025-01-07 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academique', '0012_classeprogression_demande_de_paiement_initie'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='DossierMinistere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule_etudiant', models.CharField(max_length=14, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_de_naissance', models.DateField()),
                ('extrait_de_naissance', models.FileField(upload_to='ministere/dossiers/extraits/')),
                ('justificatif_d_identite', models.FileField(upload_to='ministere/dossiers/pieces/')),
                ('collante_du_bac', models.FileField(upload_to='ministere/dossiers/bacs')),
                ('telephone', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_filiere', to='gestion_academique.filiere')),
            ],
            options={
                'verbose_name': 'DossierMinistere',
                'verbose_name_plural': 'DossierMinisteres',
            },
        ),
    ]
