# Generated by Django 4.2.3 on 2025-02-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academique', '0013_pointage_code_dossierministere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
