# Generated by Django 5.1.5 on 2025-03-02 22:36

import gestion_academique.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academique', '0014_alter_classe_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident_perm', models.CharField(max_length=150, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=150)),
                ('filiere', models.CharField(max_length=150)),
                ('niveau', models.CharField(max_length=150)),
                ('classe', models.CharField(max_length=150)),
                ('elite_id', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(max_length=150)),
                ('sexe', models.CharField(max_length=150)),
                ('contact', models.CharField(blank=True, max_length=150, null=True)),
                ('photo', models.TextField()),
                ('etablissement', models.CharField(max_length=150)),
                ('code_unique', models.CharField(default=gestion_academique.models.generate_unique_code, max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
