# Generated by Django 5.1.5 on 2026-03-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academique', '0015_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classeprogression',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='classeprogression',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='pointage',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='dossierministere',
            name='filiere',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AlterModelOptions(
            name='classe',
            options={'ordering': ['nom'], 'verbose_name': 'Classe', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterField(
            model_name='classe',
            name='closed',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='ClasseProgression',
        ),
        migrations.DeleteModel(
            name='Pointage',
        ),
        migrations.DeleteModel(
            name='DossierMinistere',
        ),
    ]
