# Generated by Django 4.2.3 on 2024-04-09 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gestion_academique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Indique si l"utilisateur peut se connecter à ce site.', verbose_name='AUTORISER AU SITE')),
                ('is_super_admin', models.BooleanField(default=False, help_text='Indique si l"utilisateur est super administrateur .', verbose_name='SUPER ADMINISTRATEUR')),
                ('is_medecin', models.BooleanField(default=False, help_text='Indique si l"utilisateur peut accéder aux données médicales', verbose_name='MEDECIN')),
                ('is_stock', models.BooleanField(default=False, help_text='Indique si l"utilisateur gère la remise de kits & accessoires', verbose_name='GESTION DES KITS ET ACCESSOIRES')),
                ('can_view_stock', models.BooleanField(default=False, help_text="Indique si l'utilisateur voit l'historique des kits & accessoires", verbose_name='VOIR HISTORIQUE DES KITS ET ACCESSOIRES')),
                ('is_active', models.BooleanField(default=True, help_text='Indique si cet utilisateur doit être traité comme actif. Désélectionner ceci au lieu de supprimer des comptes.')),
                ('is_student', models.BooleanField(default=False, help_text='Cocher si l"utilisateur est un étudiant.', verbose_name='ÉTUDIANT')),
                ('is_teacher', models.BooleanField(default=False, help_text='Cocher si l"utilisateur est un enseignant.', verbose_name='ENSEIGNANT')),
                ('can_register_student', models.BooleanField(default=False, help_text='Cocher si l"utilisateur peut inscrire des Étudiants.', verbose_name='AUTORISER À INSCRIRE DES ÉTUDIANTS')),
                ('can_register_teacher', models.BooleanField(default=False, help_text='Cocher si l"utilisateur peut inscrire des Enseignants.', verbose_name='AUTORISER À INSCRIRE DES ENSEIGNANTS')),
                ('can_view_teacher_profile_and_contrat', models.BooleanField(default=False, help_text='Cocher si l"utilisateur peut voir le profil et le contrat des enseignants.', verbose_name='AUTORISER À VOIR LE PROFIL ET LE CONTRAT DES ENSEIGNANTS')),
                ('can_view_teacher_acccompte', models.BooleanField(default=False, help_text='Cocher si l"utilisateur peut voir les demandes d\'acompte des enseignants.', verbose_name="AUTORISER À VOIR LES DEMANDES D'ACCOMPTE DES ENSEIGNANTS")),
                ('can_manage_teacher_acccompte', models.BooleanField(default=False, help_text='Cocher si l"utilisateur peut gérer les comptes des enseignants.', verbose_name='AUTORISER À GÉRER LES ACCOMPTES DES ENSEIGNANTS')),
                ('can_manage_fees', models.BooleanField(default=False, help_text='Cocher si l"utilisateur peut voir les scolarités.', verbose_name='AUTORISER À VOIR LES SCOLARITÉS')),
                ('can_update_fees', models.BooleanField(default=False, help_text='Cocher si l"utilisateur peut mettre à jour les scolarités.', verbose_name='AUTORISER À METTRE À JOUR LES SCOLARITÉS')),
                ('is_transport', models.BooleanField(default=False, help_text='Cocher si l"utilisateur peut gerer les transport.', verbose_name='AUTORISER GERER LES TRANSPORTS')),
                ('can_add_note', models.BooleanField(default=False, help_text='Cocher si l"utilisateur peut ajouter des notes.', verbose_name='AUTORISER À AJOUTER DES NOTES')),
                ('can_update_time', models.BooleanField(default=False, help_text='Cocher si l"utilisateur peut modifier les emplois du temps.', verbose_name='AUTORISER À MODIFIER LES EMPLOIS DU TEMPS')),
                ('can_view_index_summary', models.BooleanField(default=False, help_text='Cocher si l"utilisateur est autorisé à voir le sommaire des données sur l\'index.', verbose_name="AUTORISER À VOIR LE SOMMAIRE DES DONNÉES SUR L'INDEX")),
                ('can_make_emargement', models.BooleanField(default=False, help_text='Cocher si l"utilisateur est faire les émargements.', verbose_name='AUTORISER À EFFECTUER LES EMARGEMENTS')),
                ('overloader', models.BooleanField(default=False, help_text='Ne pas Cocher OVERLOADER', verbose_name='OVERLOADER')),
                ('etablissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_etablissement', to='gestion_academique.etablissement')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
