# Generated by Django 5.1.5 on 2025-12-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('gestion_academique', '0002_alter_etablissement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='classe',
            field=models.ManyToManyField(blank=True, to='gestion_academique.classe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gestion',
            field=models.ManyToManyField(blank=True, to='gestion_academique.etablissement'),
        ),
    ]
