# Generated by Django 4.2.3 on 2024-07-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_diplome',
            field=models.BooleanField(default=False, help_text='Cocher si l"utilisateur autorisé À GERER LES DIPLOMES ET CERTIFICATS.', verbose_name='AUTORISER À GERER LES DIPLOMES ET CERTIFICATS'),
        ),
    ]
