# Generated by Django 5.1.5 on 2025-12-04 03:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_classe_alter_user_gestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 12, 4, 3, 1, 2, 394817, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
