# Generated by Django 4.2.3 on 2024-11-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academique', '0009_classeprogression_alter_classe_options_pointage_and_more'),
        ('authentication', '0002_user_can_manage_diplome'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='classe',
            field=models.ManyToManyField(blank=True, null=True, to='gestion_academique.classe'),
        ),
        migrations.AddField(
            model_name='user',
            name='see_all_resume_progress',
            field=models.BooleanField(default=False, help_text='see_all_resume_progress', verbose_name='see_all_resume_progress'),
        ),
    ]
