# Generated by Django 4.2.3 on 2024-11-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academique', '0010_alter_classe_options'),
        ('authentication', '0003_user_classe_user_see_all_resume_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gestion',
            field=models.ManyToManyField(blank=True, null=True, to='gestion_academique.etablissement'),
        ),
    ]
