# Generated by Django 4.2.3 on 2024-12-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_gestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_comptable',
            field=models.BooleanField(default=False, help_text='is_comptable', verbose_name='is_comptable'),
        ),
    ]
