# Generated by Django 4.2.3 on 2024-12-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_is_comptable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_program_manger_for_online_courses',
            field=models.BooleanField(default=False, help_text='is_program_manger_for_online_courses', verbose_name='is_program_manger_for_online_courses'),
        ),
    ]
