# Generated by Django 4.2.3 on 2025-01-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_is_program_manger_for_online_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='can_add_note',
            field=models.BooleanField(default=False, help_text='Cocher si l"utilisateur peut MODIFIER LES MAQUETTES.', verbose_name='AUTORISER À MODIFIER LES MAQUETTES'),
        ),
    ]
