# Generated by Django 4.2.3 on 2025-01-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_user_can_add_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_update_maquette',
            field=models.BooleanField(default=False, help_text='Cocher si l"utilisateur peut MODIFIER LES MAQUETTES.', verbose_name='AUTORISER À MODIFIER LES MAQUETTES'),
        ),
        migrations.AlterField(
            model_name='user',
            name='can_add_note',
            field=models.BooleanField(default=False, help_text='Cocher si l"utilisateur peut ajouter des notes.', verbose_name='AUTORISER À AJOUTER DES NOTES'),
        ),
    ]
