# Generated by Django 5.1.5 on 2026-03-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_can_update_maquette_alter_user_can_add_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_update_maquette',
        ),
        migrations.RemoveField(
            model_name='user',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gestion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_comptable',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_program_manger_for_online_courses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='see_all_resume_progress',
        ),
    ]
