# Generated by Django 4.2.3 on 2024-04-09 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonction', models.CharField(max_length=150)),
                ('a_propos', models.TextField(default='')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='etudiants.etudiant')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('EXPERIENCE PROFESSIONNELLE', 'EXPERIENCE PROFESSIONNELLE'), ('EDUCATION', 'EDUCATION')], max_length=100)),
                ('intitule', models.CharField(help_text='Nom de la structure', max_length=250)),
                ('etablissement', models.CharField(help_text="Nom de la structure ou a eu lieu l'activité", max_length=100)),
                ('debut', models.CharField(help_text="Date de debut de l'activité", max_length=100)),
                ('fin', models.CharField(help_text="Date de fin de l'activité", max_length=100)),
                ('description', models.TextField(default='', help_text="Description de l'activité")),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_info', to='curriculum.resume')),
            ],
            options={
                'verbose_name': 'Information',
                'verbose_name_plural': 'Informations',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('COMPETENCE', 'COMPETENCE'), ('LOISIR', 'LOISIR'), ('LANGUE', 'LANGUE'), ('ATOUT', 'ATOUT'), ('AUTRES', 'AUTRES')], max_length=50)),
                ('intitule', models.CharField(help_text="Titre de l'information", max_length=250)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_data', to='curriculum.resume')),
            ],
            options={
                'verbose_name': 'Data',
                'verbose_name_plural': 'Datas',
            },
        ),
    ]
