# Generated by Django 5.1.5 on 2025-11-12 16:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiants', '0001_initial'),
        ('gestion_academique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(default=django.utils.timezone.now)),
                ('to_date', models.DateField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant_trajet', to='etudiants.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=50)),
                ('immatriculation', models.CharField(max_length=155, unique=True)),
                ('nombre_places', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_etablissement', to='gestion_academique.etablissement')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField(default=0)),
                ('source', models.CharField(blank=True, max_length=150, null=True)),
                ('reference', models.CharField(blank=True, max_length=150, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('wave_launch_url', models.CharField(blank=True, max_length=250, null=True)),
                ('wave_id', models.CharField(blank=True, max_length=250, null=True)),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnement_paiement', to='transport.abonnement')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=100)),
                ('arrive', models.CharField(max_length=100)),
                ('cout_mensuel', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_trajet', to='transport.car')),
            ],
        ),
        migrations.AddField(
            model_name='abonnement',
            name='trajet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajet_abonnements', to='transport.trajet'),
        ),
    ]
