# Generated by Django 4.2.3 on 2024-04-09 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_academique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtablissementDorigine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=200)),
                ('dren', models.CharField(max_length=100)),
                ('type_etablissement', models.CharField(choices=[('PRIVE', 'PRIVE'), ('PUBLIC', 'PUBLIC')], max_length=20)),
                ('statut', models.CharField(default='MIXTE', max_length=10)),
            ],
            options={
                'verbose_name': 'Etablissement Dorigine',
                'verbose_name_plural': "Etablissements D'origines",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='SessionSoutenanceNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='soutenance/fichier')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('carte_etudiant', models.BooleanField(default=False)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=28)),
                ('ss', models.CharField(blank=True, max_length=28, null=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_etablissement', to='gestion_academique.etablissement')),
            ],
            options={
                'verbose_name': 'Session Soutenance',
                'verbose_name_plural': 'Session Soutenances',
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('prenom', models.CharField(max_length=120)),
                ('type_etudiant', models.CharField(choices=[('Affecté(e)', 'Affecté(e)'), ('Non Affecté(e)', 'Non Affecté(e)')], max_length=14)),
                ('date_de_naissance', models.DateField()),
                ('lieu_de_naissance', models.CharField(max_length=50)),
                ('matricule_mers', models.CharField(max_length=50)),
                ('numero_table_bac', models.CharField(max_length=50)),
                ('matricule_menet', models.CharField(max_length=50)),
                ('nationalite', django_countries.fields.CountryField(max_length=2)),
                ('matricule', models.CharField(blank=True, max_length=50, null=True)),
                ('lieu_de_residence', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], max_length=10)),
                ('serie_bac', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=10)),
                ('contactparent', models.CharField(max_length=10)),
                ('photo', models.FileField(blank=True, null=True, upload_to='etudiant/photo')),
                ('extrait', models.FileField(blank=True, null=True, upload_to='etudiant/extrait')),
                ('diplome', models.FileField(blank=True, null=True, upload_to='etudiant/diplome')),
                ('fiche_orientation', models.FileField(blank=True, null=True, upload_to='etudiant/fiche_orientation')),
                ('piece', models.FileField(blank=True, null=True, upload_to='etudiant/piece')),
                ('dictaticiel', models.BooleanField(default=False)),
                ('sans_bac', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('extrait_depose', models.BooleanField(default=False)),
                ('cmu', models.BooleanField(default=False)),
                ('piece_depose', models.BooleanField(default=False)),
                ('photo_depose', models.BooleanField(default=False)),
                ('diplome_depose', models.BooleanField(default=False)),
                ('fiche_orientation_depose', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('carte_etudiant', models.BooleanField(default=False)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('code_paiement', models.CharField(editable=False, max_length=10)),
                ('photo_updated', models.BooleanField(default=False)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant_etablissement', to='gestion_academique.etablissement')),
                ('etablissement_d_origine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant_etablissement_origine', to='etudiants.etablissementdorigine')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etudiant',
                'verbose_name_plural': 'Etudiants',
            },
        ),
        migrations.CreateModel(
            name='AttestationNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('sexe', models.CharField(max_length=50)),
                ('matricule', models.CharField(max_length=50)),
                ('date_de_naissance', models.DateField()),
                ('lieu_de_naissance', models.CharField(max_length=150)),
                ('pays', models.CharField(max_length=150)),
                ('filiere', models.CharField(max_length=150)),
                ('cycle', models.CharField(max_length=150)),
                ('niveau', models.CharField(max_length=150)),
                ('annee_academique', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('carte_etudiant', models.BooleanField(default=False)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=28)),
                ('ss', models.CharField(blank=True, max_length=28, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AttestationNew_session', to='etudiants.sessionsoutenancenew')),
            ],
            options={
                'verbose_name': 'AttestationNew',
                'verbose_name_plural': 'AttestationNews',
            },
        ),
    ]
