# Generated by Django 5.1.5 on 2025-12-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='code_paiement',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='contact',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='contactparent',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='serie_bac',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='sexe',
            field=models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], max_length=50),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='type_etudiant',
            field=models.CharField(choices=[('Affecté(e)', 'Affecté(e)'), ('Non Affecté(e)', 'Non Affecté(e)')], max_length=50),
        ),
    ]
