# Generated by Django 4.2.3 on 2024-07-05 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_academique', '0001_initial'),
        ('etudiants', '0002_sessiondiplome_diplome'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='diplome/fichier')),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('carte_etudiant', models.BooleanField(default=False)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=28)),
                ('ss', models.CharField(blank=True, max_length=28, null=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_certificat_etablissement', to='gestion_academique.etablissement')),
            ],
            options={
                'verbose_name': 'Certificat Session',
                'verbose_name_plural': 'Certificat Session',
            },
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('diplome', models.CharField(max_length=150)),
                ('date_de_naissance', models.DateField()),
                ('lieu_de_naissance', models.CharField(max_length=150)),
                ('cycle', models.CharField(max_length=150)),
                ('niveau', models.CharField(max_length=150)),
                ('annee_academique', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=28)),
                ('programme', models.CharField(max_length=28)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificat_session', to='etudiants.certificatsession')),
            ],
            options={
                'verbose_name': 'Certificat',
                'verbose_name_plural': 'Certificats',
            },
        ),
    ]
